# Generated by Django 5.2 on 2025-08-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('category', models.CharField(choices=[('park', 'Park'), ('market', 'Targ/Market'), ('garden', 'Ogród'), ('recycle', 'Punkt recyklingu'), ('other', 'Inne')], default='other', max_length=20, verbose_name='Kategoria')),
                ('city', models.CharField(max_length=120, verbose_name='Miasto')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adres')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Szerokość (lat)')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Długość (lng)')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eko-miejsce',
                'verbose_name_plural': 'Eko-miejsca',
                'ordering': ['city', 'name'],
            },
        ),
    ]
