# Generated by Django 5.2 on 2025-08-08 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_ecoplace_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ocena (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Komentarz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.ecoplace', verbose_name='Miejsce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Opinia o miejscu',
                'verbose_name_plural': 'Opinie o miejscach',
                'ordering': ['-created_at'],
                'unique_together': {('place', 'user')},
            },
        ),
    ]
