# Generated by Django 5.2 on 2025-08-08 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placereview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Zatwierdzony'),
        ),
        migrations.CreateModel(
            name='PlaceReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField(default=True, verbose_name='Pomocny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='places.placereview', verbose_name='Opinia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Głos na opinię',
                'verbose_name_plural': 'Głosy na opinie',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
