# Generated by Django 5.2 on 2025-05-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(default=' ', max_length=250, verbose_name='Адрес (улица, дом)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес (кв., офис - необязательно)'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=' ', max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Польша', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=' ', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=' ', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=' ', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=' ', max_length=20, verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
    ]
