# Generated by Django 5.2 on 2025-05-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_address_line_1_order_address_line_2_order_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
