# Generated by Django 5.2 on 2025-05-22 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionBoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa Boxa Subskrypcyjnego')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za okres')),
                ('billing_period', models.CharField(choices=[('week', 'Tygodniowo'), ('month', 'Miesięcznie')], default='month', max_length=10, verbose_name='Okres rozliczeniowy')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscription_boxes/', verbose_name='Obrazek Boxa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny (dostępny do subskrypcji)')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Price ID')),
            ],
            options={
                'verbose_name': 'Typ Boxa Subskrypcyjnego',
                'verbose_name_plural': 'Typy Boxów Subskrypcyjnych',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktywna'), ('paused', 'Wstrzymana'), ('canceled', 'Anulowana'), ('pending_payment', 'Oczekuje na płatność'), ('past_due', 'Zaległa płatность')], default='pending_payment', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Data rozpoczęcia')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Koniec bieżącego opłaconego okresu')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Subscription ID')),
                ('box_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='store.subscriptionboxtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subskrypcja Użytkownika',
                'verbose_name_plural': 'Subskrypcje Użytkowników',
                'ordering': ['-start_date'],
            },
        ),
    ]
