# Generated by Django 5.2 on 2025-05-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_subscriptionboxtype_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, verbose_name='Anulować na koniec okresu?'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Początek bieżącego okresu'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Koniec bieżącego okresu'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia w systemie'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Aktywna'), ('trialing', 'Okres próbny'), ('paused', 'Wstrzymana'), ('canceled', 'Anulowana'), ('incomplete', 'Niekompletna'), ('incomplete_expired', 'Niekompletna (wygasła)'), ('pending_payment', 'Oczekuje na płatność'), ('past_due', 'Zaległa płatność')], default='pending_payment', max_length=25),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stripe Subscription ID'),
        ),
    ]
