# Generated by Django 5.2 on 2025-05-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/originals/%Y/%m/%d/', verbose_name='Изображение (оригинал)'),
        ),
    ]
