# Generated by Django 5.2 on 2025-05-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_image_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_customer_id',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
