# Generated by Django 5.2 on 2025-06-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eco_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Эко-очки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_points_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление очков'),
        ),
    ]
