# Generated by Django 5.2 on 2025-06-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_usersubscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, verbose_name='Anulować na koniec okresu?'),
        ),
    ]
