# Generated by Django 5.2 on 2025-06-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_usersubscription_cancel_at_period_end'),
        ('store', '0023_remove_discount_coupon'),
    ]

    operations = [
    ]
