# Generated by Django 5.2 on 2025-06-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_merge_20250606_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod kuponu')),
                ('valid_from', models.DateTimeField(verbose_name='Początek ważności')),
                ('valid_to', models.DateTimeField(verbose_name='Koniec ważności')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Zniżka (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Kupon rabatowy',
                'verbose_name_plural': 'Kupony rabatowe',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Zniżka (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.coupon', verbose_name='Kupon'),
        ),
    ]
