# Generated by Django 5.2 on 2025-06-13 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challenge_reward_coupon'),
        ('store', '0025_coupon_order_discount_order_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przyznania')),
                ('is_used', models.BooleanField(default=False, verbose_name='Czy wykorzystany')),
                ('challenge_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_user_coupons', to='challenges.challenge', verbose_name='Wyzwanie (źródło kuponu)')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='store.coupon', verbose_name='Kupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Kupon użytkownika',
                'verbose_name_plural': 'Kupony użytkowników',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
