# Generated by Django 5.2 on 2025-08-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data wykorzystania'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_user_coupons', to='store.order', verbose_name='Zamówienie (wykorzystanie kuponu)'),
        ),
    ]
