# Generated by Django on 2025-08-08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email potwierdzający wysłany'),
        ),
    ]
