# Generated by Django 5.2 on 2025-08-22 18:27

import django.core.files.storage
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=store.models.profile_avatar_upload_to),
        ),
    ]
