# Generated by Django 5.2 on 2025-08-25 11:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_homepagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionboxtype',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='subscription_boxes/', verbose_name='Obrazek Boxa'),
        ),
    ]
