# Generated by Django 5.2 on 2025-08-25 12:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_subscriptionboxtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='box_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='homepage/', verbose_name='Obrazek sekcji box'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='homepage/', verbose_name='Obrazek hero (góra)'),
        ),
    ]
