# Generated by Django 5.2 on 2025-06-04 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0001_initial'),
        ('store', '0022_alter_usersubscription_cancel_at_period_end'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Kategoria aktywności', 'verbose_name_plural': 'Kategorie aktywności'},
        ),
        migrations.AlterModelOptions(
            name='emissionfactor',
            options={'ordering': ['activity_category__order', 'activity_category__name', 'order', 'name'], 'verbose_name': 'Współczynnik emisji', 'verbose_name_plural': 'Współczynniki emisji'},
        ),
        migrations.AlterModelOptions(
            name='reductiontip',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'Porada redukująca ślad', 'verbose_name_plural': 'Porady redukujące ślad'},
        ),
        migrations.AlterModelOptions(
            name='userfootprintsession',
            options={'ordering': ['-calculated_at'], 'verbose_name': 'Sesja obliczania śladu węglowego', 'verbose_name_plural': 'Sesje obliczeń śladu węglowego'},
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis kategorii'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Klasa ikony (np. Bootstrap Icons)'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa kategorii'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność wyświetlania'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug (do URL)'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='activity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='carbon_calculator.activitycategory', verbose_name='Kategoria aktywności'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='co2_kg_per_unit',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Emisja CO2 (kg) na jednostkę'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='data_source_info',
            field=models.TextField(blank=True, null=True, verbose_name='Źródło danych dla współczynnika (raport, rok)'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Szczegółowy opis czynnika (dla administratora)'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='form_field_options',
            field=models.JSONField(blank=True, help_text='Dla "select": {"option_value1": "Etykieta opcji 1", "option_value2": "Etykieta opcji 2"}. Wartość to mnożnik dla co2_kg_per_unit lub wartość do obliczeń.', null=True, verbose_name="Opcje dla pola 'select' (JSON)"),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='form_field_type',
            field=models.CharField(choices=[('number', 'Pole liczbowe'), ('select', 'Lista rozwijana')], default='number', max_length=20, verbose_name='Typ pola w formularzu'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='form_help_text',
            field=models.TextField(blank=True, null=True, verbose_name='Podpowiedź do pola w formularzu'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='form_placeholder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tekst podpowiedzi (placeholder) dla pola liczbowego'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='form_question_text',
            field=models.TextField(verbose_name='Treść pytania dla użytkownika w formularzu'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny (używać w kalkulatorze)'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa wewnętrzna czynnika/aktywności'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność pytania w kategorii'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='periodicity_options_for_form',
            field=models.JSONField(blank=True, help_text='Przykład: {"per_week": {"label": "na tydzień", "annual_multiplier": 52}, "per_month": {"label": "na miesiąc", "annual_multiplier": 12}}. Jeśli puste, zakłada się wartość roczną lub określoną w unit_name.', null=True, verbose_name='Opcje częstotliwości dla wprowadzania (JSON)'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='unit_name',
            field=models.CharField(max_length=50, verbose_name='Jednostka miary do obliczeń CO2'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Obowiązuje od'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Obowiązuje do'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='applies_to_categories',
            field=models.ManyToManyField(blank=True, help_text='Jeśli określono, porada będzie wyświetlana, jeśli są emisje w tych kategoriach (można doprecyzować w trigger_conditions_json)', to='carbon_calculator.activitycategory', verbose_name='Dotyczy kategorii aktywności'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='description_template',
            field=models.TextField(help_text='Użyj placeholderów: {{user_input_X}} dla wartości czynnika X, {{annual_emission_category_Y}} dla emisji w kategorii Y, {{potential_annual_savings_kg}} dla szacowanych oszczędności.', verbose_name='Szablon opisu porady'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='estimated_co2_reduction_kg_annual_logic',
            field=models.JSONField(blank=True, null=True, verbose_name='Logika szacowania rocznego ograniczenia CO2 (JSON)'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='external_link_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tekst do zewnętrznego linku'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='external_link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Zewnętrzny link (do artykułu, źródła)'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Klasa ikony do porady'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Porada aktywna'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Priorytet (im wyższy, tym ważniejszy)'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='suggested_products',
            field=models.ManyToManyField(blank=True, related_name='reduction_tips', to='store.product', verbose_name='Sugerowane produkty EcoMarket'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł porady'),
        ),
        migrations.AlterField(
            model_name='reductiontip',
            name='trigger_conditions_json',
            field=models.JSONField(blank=True, help_text='Określa, kiedy porada jest odpowiednia. Jeśli puste, porada wyświetlana jest zawsze (jeśli aktywna).', null=True, verbose_name='Warunki wyświetlania porady (JSON)'),
        ),
        migrations.AlterField(
            model_name='userfootprintsession',
            name='calculated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data obliczenia'),
        ),
        migrations.AlterField(
            model_name='userfootprintsession',
            name='calculation_version',
            field=models.CharField(default='1.0', max_length=50, verbose_name='Wersja kalkulatora/metodologii'),
        ),
        migrations.AlterField(
            model_name='userfootprintsession',
            name='category_breakdown_kg_annual',
            field=models.JSONField(blank=True, null=True, verbose_name='Roczny podział na kategorie (kg CO2-ekw.)'),
        ),
        migrations.AlterField(
            model_name='userfootprintsession',
            name='inputs_data',
            field=models.JSONField(verbose_name='Dane wprowadzone przez użytkownika i ich kontekst'),
        ),
        migrations.AlterField(
            model_name='userfootprintsession',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Klucz sesji (dla anonimowych)'),
        ),
        migrations.AlterField(
            model_name='userfootprintsession',
            name='total_co2_emissions_kg_annual',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Całkowity roczny ślad węglowy (kg CO2-ekw.)'),
        ),
        migrations.AlterField(
            model_name='userfootprintsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
