# Generated by Django 5.2 on 2025-08-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0002_alter_activitycategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kod kraju/regionu')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa regionu/kraju')),
                ('grid_intensity_kg_per_kwh', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Intensywność sieci (kg CO2/kWh)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Domyślny region')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiony',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='use_region_grid_intensity',
            field=models.BooleanField(default=False, verbose_name='Użyj intensywności sieci regionu (zamiast co2/kg na jednostkę)'),
        ),
    ]
