# Generated by Django 5.2 on 2025-08-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0003_region_emissionfactor_use_region_grid_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='max_reasonable_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Maksymalna rozsądna wartość'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='min_reasonable_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Minimalna rozsądna wartość'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='per_household',
            field=models.BooleanField(default=False, verbose_name='Dotyczy gospodarstwa domowego (dzielić na liczbę osób)'),
        ),
    ]
