# Generated by Django 5.2 on 2025-08-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0004_emissionfactor_max_reasonable_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='form_field_options',
            field=models.JSONField(blank=True, help_text='Dla "select": {"1": "Etykieta 1", "0.15": "Etykieta 2"}. Klucze muszą być LICZBAMI (np. "1", "0.15"), bo są używane bezpośrednio w obliczeniach jako mnożnik/wartość.', null=True, verbose_name="Opcje dla pola 'select' (JSON)"),
        ),
    ]
