# Generated by Django 5.2 on 2025-08-08 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Usunięta'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/', verbose_name='Plik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message', verbose_name='Wiadomość')),
            ],
            options={
                'verbose_name': 'Załącznik wiadomości',
                'verbose_name_plural': 'Załączniki wiadomości',
            },
        ),
        migrations.CreateModel(
            name='ChatInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('accepted', 'Zaakceptowane'), ('declined', 'Odrzucone')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_invites', to=settings.AUTH_USER_MODEL, verbose_name='Zaproszony')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_invites', to=settings.AUTH_USER_MODEL, verbose_name='Zapraszający')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.chatroom', verbose_name='Pokój')),
            ],
            options={
                'verbose_name': 'Zaproszenie do pokoju',
                'verbose_name_plural': 'Zaproszenia do pokoi',
                'unique_together': {('room', 'invitee', 'status')},
            },
        ),
    ]
