# Generated by Django 5.2 on 2025-08-22 18:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='chat_attachments/%Y/%m/', verbose_name='Plik'),
        ),
    ]
