# Generated by Django 5.2 on 2025-08-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentrating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commentrating',
            new_name='blog_commen_comment_d29877_idx',
            old_name='blog_commen_comment_8b9849_idx',
        ),
    ]
