# Generated by Django 5.2 on 2025-08-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_moderation_fields_blogban'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogban',
            new_name='blog_blogba_active_36f92a_idx',
            old_name='blog_ban_active_idx',
        ),
        migrations.RenameIndex(
            model_name='blogban',
            new_name='blog_blogba_ip_addr_4b8830_idx',
            old_name='blog_ban_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='blogban',
            new_name='blog_blogba_user_id_765f2c_idx',
            old_name='blog_ban_user_idx',
        ),
    ]
