# Generated by Django 5.2 on 2025-06-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название значка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS класс иконки')),
            ],
            options={
                'verbose_name': 'Значок (Бейдж)',
                'verbose_name_plural': 'Значки (Бейджи)',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название челленджа')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug (для URL)')),
                ('description', models.TextField(verbose_name='Полное описание и правила')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание (для списка)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='challenges_images/', verbose_name='Изображение челленджа')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('points_for_completion', models.PositiveIntegerField(default=0, verbose_name='Очки за выполнение')),
                ('badge_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название значка (если есть)')),
                ('badge_icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS класс иконки значка')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('active', 'Активный'), ('completed', 'Завершен (период прошел)'), ('archived', 'Архивный')], default='upcoming', max_length=10, verbose_name='Статус челленджа')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Повторяющийся челлендж?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Эко-Челлендж',
                'verbose_name_plural': 'Эко-Челленджи',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to_users', to='challenges.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Значок пользователя',
                'verbose_name_plural': 'Значки пользователей',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Присоединился'), ('in_progress', 'В процессе'), ('completed_pending_review', 'Выполнен (ожидает проверки)'), ('completed_approved', 'Выполнен (подтвержден)'), ('failed', 'Не выполнен')], default='joined', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата фактического выполнения')),
                ('user_notes', models.TextField(blank=True, null=True, verbose_name='Заметки пользователя/Отчет')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участие в челлендже',
                'verbose_name_plural': 'Участия в челленджах',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
