# Generated by Django 5.2 on 2025-06-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Odznaka (Badge)', 'verbose_name_plural': 'Odznaki (Badge)'},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-start_date', 'title'], 'verbose_name': 'Eko-Wyzwanie', 'verbose_name_plural': 'Eko-Wyzwania'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-awarded_at'], 'verbose_name': 'Odznaka użytkownika', 'verbose_name_plural': 'Odznaki użytkowników'},
        ),
        migrations.AlterModelOptions(
            name='userchallengeparticipation',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Udział w wyzwaniu', 'verbose_name_plural': 'Udziały w wyzwaniach'},
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywne (widoczne dla użytkowników)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='To szablon do powielania'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='template_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='challenges.challenge', verbose_name='Szablon tego wyzwania'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS klasa ikony'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa odznaki'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='badge_icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS klasa ikony odznaki'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='badge_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa odznaki (jeśli jest)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(verbose_name='Pełny opis i zasady'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenges_images/', verbose_name='Obrazek wyzwania'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Czy wyzwanie cykliczne?'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points_for_completion',
            field=models.PositiveIntegerField(default=0, verbose_name='Punkty za ukończenie'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Krótki opis (do listy)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug (do URL)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Nadchodzące'), ('active', 'Aktywne'), ('completed', 'Zakończone (okres minął)'), ('archived', 'Zarchiwizowane')], default='upcoming', max_length=10, verbose_name='Status wyzwania'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nazwa wyzwania'),
        ),
        migrations.AlterField(
            model_name='userchallengeparticipation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data faktycznego ukończenia'),
        ),
        migrations.AlterField(
            model_name='userchallengeparticipation',
            name='status',
            field=models.CharField(choices=[('joined', 'Dołączył'), ('in_progress', 'W trakcie'), ('completed_pending_review', 'Ukończone (oczekuje na weryfikację)'), ('completed_approved', 'Ukończone (zatwierdzone)'), ('failed', 'Nieukończone')], default='joined', max_length=30),
        ),
        migrations.AlterField(
            model_name='userchallengeparticipation',
            name='user_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notatki użytkownika/Raport'),
        ),
    ]
