# Generated by Django 5.2 on 2025-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_badge_options_alter_challenge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='badge_icon_class_reward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS klasa ikony odznaki-nagrody'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='badge_name_reward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa odznaki-nagrody'),
        ),
    ]
