# Generated by Django 5.2 on 2025-06-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_badge_icon_class_reward_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['start_date'], 'verbose_name': 'Челлендж', 'verbose_name_plural': 'Челленджи'},
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='badge_icon_class',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='badge_name',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='badge_icon_class_reward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS класс иконки награды-значка'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='badge_name_reward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название награды-значка'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenges_images/', verbose_name='Изображение челленджа'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен (для отображения)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name="Повторяющийся (устарело, используйте 'Это шаблон')"),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Это шаблон для повторения'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points_for_completion',
            field=models.IntegerField(default=10, verbose_name='Баллы за выполнение'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Предстоящий'), ('active', 'Активный'), ('completed', 'Завершено (пользователем)'), ('failed', 'Провалено (пользователем)'), ('completed_period', 'Завершено (период истек)'), ('archived', 'Архивировано')], default='upcoming', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='template_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='challenges.challenge', verbose_name='Шаблон этого челленджа'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название челленджа'),
        ),
    ]
