# Generated by Django 5.2 on 2025-06-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challenge_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_recurring',
        ),
    ]
