# Generated by Django 5.2 on 2025-06-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_remove_challenge_is_recurring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Odznaka', 'verbose_name_plural': 'Odznaki'},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['start_date'], 'verbose_name': 'Wyzwanie', 'verbose_name_plural': 'Wyzwania'},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='badge_icon_class_reward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS klasa ikony odznaki'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='badge_name_reward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa odznaki za wyzwanie'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(verbose_name='Pełny opis'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenges_images/', verbose_name='Образек wyzwania'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywne (widoczne)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Szablon powtarzalny'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points_for_completion',
            field=models.IntegerField(default=10, verbose_name='Punkty za ukończenie'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Nadchodzące'), ('active', 'Aktywne'), ('completed', 'Ukończone (przez użytkownika)'), ('failed', 'Nieukończone (przez użytkownika)'), ('completed_period', 'Zakończone (okres minął)'), ('archived', 'Zarchiwizowane')], default='upcoming', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='template_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='challenges.challenge', verbose_name='Szablon tego wyzwania'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nazwa wyzwania'),
        ),
    ]
