# Generated by Django 5.2 on 2025-06-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_badge_options_alter_challenge_options_and_more'),
        ('store', '0025_coupon_order_discount_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='reward_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_challenges', to='store.coupon', verbose_name='Kupón za ukończenie wyzwania'),
        ),
    ]
