# Generated by Django 5.2 on 2025-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_participation_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenges_images/', verbose_name='Obrazek wyzwania'),
        ),
    ]
